<?xml version="1.0"?>
<!DOCTYPE COVParksFacilities [
<!ELEMENT COVParksFacilities ( Park+ ) >
<!ELEMENT Park ( Name, Official, StreetNumber, StreetName, EWStreet, NSStreet, GoogleMapDest, Hectare, Neighbourhood?, Advisories, Facilities ) >
<!ELEMENT Name ( #PCDATA ) >
<!ELEMENT Official ( #PCDATA ) >
<!ELEMENT StreetNumber ( #PCDATA ) >
<!ELEMENT StreetName ( #PCDATA ) >
<!ELEMENT EWStreet ( #PCDATA ) >
<!ELEMENT NSStreet ( #PCDATA ) >
<!ELEMENT GoogleMapDest ( #PCDATA ) >
<!ELEMENT Hectare ( #PCDATA ) >
<!ELEMENT Neighbourhood ( NeighbourhoodName, NeighbourhoodURL ) >
<!ELEMENT NeighbourhoodName ( #PCDATA ) >
<!ELEMENT NeighbourhoodURL ( #PCDATA ) >
<!ELEMENT Advisories ( Advisory* ) >
<!ELEMENT Advisory ( DateLast, AdvisoryText, URL ) >
<!ELEMENT DateLast ( #PCDATA ) >
<!ELEMENT AdvisoryText ( ANY ) >
<!ELEMENT URL ( #PCDATA ) >
<!ELEMENT Facilities ( Facility*, SpecialFeature?, Washroom* ) >
<!ELEMENT Facility ( FacilityCount, FacilityType, FacilityURL? ) >
<!ELEMENT FacilityCount ( #PCDATA ) >
<!ELEMENT FacilityType ( #PCDATA ) >
<!ELEMENT FacilityURL ( #PCDATA ) >
<!ELEMENT SpecialFeature ( #PCDATA ) >
<!ELEMENT Washroom ( Location, Notes, SummerHours, WinterHours  ) >
<!ELEMENT Location ( #PCDATA ) >
<!ELEMENT Notes ( #PCDATA ) >
<!ELEMENT SummerHours ( #PCDATA ) >
<!ELEMENT WinterHours ( #PCDATA ) >
<!ELEMENT SpecialNames ( SpecialName* ) >
<!ELEMENT SpecialName ( #PCDATA ) >
<!ATTLIST Park ID CDATA #REQUIRED >
]>
<COVParksFacilities>
	<Park ID="1">
		<Name>Arbutus Village Park</Name>
		<Official>1</Official>
		<StreetNumber>4202</StreetNumber>
		<StreetName>Valley Drive</StreetName>
		<EWStreet>King Edward Avenue</EWStreet>
		<NSStreet>Valley Drive</NSStreet>
		<GoogleMapDest>49.249783,-123.155250</GoogleMapDest>
		<Hectare>1.41</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Arbutus Ridge</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/arbutus_ridge/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="2">
		<Name>Carnarvon Park</Name>
		<Official>1</Official>
		<StreetNumber>2995</StreetNumber>
		<StreetName>W 19th Avenue</StreetName>
		<EWStreet>W 19th Avenue</EWStreet>
		<NSStreet>Mackenzie Street</NSStreet>
		<GoogleMapDest>49.256555,-123.171406</GoogleMapDest>
		<Hectare>3.79</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Arbutus Ridge</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/arbutus_ridge/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Field Houses</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Softball</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>3</FacilityCount>
				<FacilityType>Baseball Diamonds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Football Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Soccer Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Washroom>
				<Location>West side, field house</Location>
				<Notes></Notes>
				<SummerHours>Dawn to Dusk</SummerHours>
				<WinterHours>Dawn to Dusk</WinterHours>
			</Washroom>
		</Facilities>
	</Park>
	<Park ID="3">
		<Name>Prince of Wales Park</Name>
		<Official>1</Official>
		<StreetNumber>4780</StreetNumber>
		<StreetName>Haggart Street</StreetName>
		<EWStreet>W 32nd Avenue</EWStreet>
		<NSStreet>Haggart Street</NSStreet>
		<GoogleMapDest>49.244397,-123.156429</GoogleMapDest>
		<Hectare>2.89</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Arbutus Ridge</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/arbutus_ridge/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Soccer Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Jogging Trails</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="4">
		<Name>Park Site on Puget Drive</Name>
		<Official>0</Official>
		<StreetNumber>4309</StreetNumber>
		<StreetName>Puget Drive</StreetName>
		<EWStreet>Puget Drive</EWStreet>
		<NSStreet>MacDonald Street</NSStreet>
		<GoogleMapDest>49.247723,-123.168194</GoogleMapDest>
		<Hectare>0.09</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Arbutus Ridge</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/arbutus_ridge/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="5">
		<Name>Park Site on Quesnel Drive</Name>
		<Official>0</Official>
		<StreetNumber>4301</StreetNumber>
		<StreetName>Quesnel Drive</StreetName>
		<EWStreet>Quesnel Drive</EWStreet>
		<NSStreet>MacKenzie Street</NSStreet>
		<GoogleMapDest>49.247623,-123.169948</GoogleMapDest>
		<Hectare>0.03</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Arbutus Ridge</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/arbutus_ridge/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="6">
		<Name>Quilchena Park</Name>
		<Official>1</Official>
		<StreetNumber>4590</StreetNumber>
		<StreetName>Magnolia Street</StreetName>
		<EWStreet>W 33rd Avenue</EWStreet>
		<NSStreet>Magnolia Street</NSStreet>
		<GoogleMapDest>49.243690,-123.148865</GoogleMapDest>
		<Hectare>7.67</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Arbutus Ridge</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/arbutus_ridge/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Baseball Diamonds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Field Houses</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Soccer Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Dogs Off-Leash Areas</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Disc Golf Courses</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Jogging Trails</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Skateboard Parks</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<SpecialFeature>Perimeter Walking Path</SpecialFeature>
			<SpecialFeature>Hellenic Garden</SpecialFeature>
			<Washroom>
				<Location>North east corner, fieldhouse</Location>
				<Notes>Caretaker on site</Notes>
				<SummerHours>Dawn to Dusk</SummerHours>
				<WinterHours>Dawn to Dusk</WinterHours>
			</Washroom>
		</Facilities>
	</Park>
	<Park ID="7">
		<Name>Ravine Park</Name>
		<Official>1</Official>
		<StreetNumber>2159</StreetNumber>
		<StreetName>W 36th Avenue</StreetName>
		<EWStreet>W 36th Avenue</EWStreet>
		<NSStreet>Arbutus Street</NSStreet>
		<GoogleMapDest>49.240902,-123.155935</GoogleMapDest>
		<Hectare>0.72</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Arbutus Ridge</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/arbutus_ridge/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="8">
		<Name>Trafalgar Park</Name>
		<Official>1</Official>
		<StreetNumber>2610</StreetNumber>
		<StreetName>W 23rd Avenue</StreetName>
		<EWStreet>W 23rd Avenue</EWStreet>
		<NSStreet>Valley Drive</NSStreet>
		<GoogleMapDest>49.25046,-123.161879</GoogleMapDest>
		<Hectare>4.85</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Arbutus Ridge</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/arbutus_ridge/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Baseball Diamonds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Cricket Pitches</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Field Houses</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Soccer Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Softball</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Ultimate Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Washroom>
				<Location>North side, fieldhouse</Location>
				<Notes>Caretaker on site</Notes>
				<SummerHours>Dawn to Dusk</SummerHours>
				<WinterHours>Dawn to Dusk</WinterHours>
			</Washroom>
		</Facilities>
	</Park>
	<Park ID="9">
		<Name>Park Site on Trafalgar Street</Name>
		<Official>0</Official>
		<StreetNumber>4600</StreetNumber>
		<StreetName>Trafalgar Street</StreetName>
		<EWStreet>W 31st Avenue</EWStreet>
		<NSStreet>Trafalgar Street</NSStreet>
		<GoogleMapDest>49.244396,-123.165105</GoogleMapDest>
		<Hectare>0.14</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Arbutus Ridge</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/arbutus_ridge/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="10">
		<Name>Andy Livingstone Park</Name>
		<Official>1</Official>
		<StreetNumber>89</StreetNumber>
		<StreetName>Expo Boulevard</StreetName>
		<EWStreet>Expo Boulevard</EWStreet>
		<NSStreet>Carrall Street</NSStreet>
		<GoogleMapDest>49.278923,-123.105500</GoogleMapDest>
		<Hectare>4.21</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Field Houses</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Field Hockey</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>3</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Softball</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Football Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Lighted Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Soccer Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Tennis Courts</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Basketball Courts</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Skateboard Parks</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Ultimate Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Washroom>
				<Location>South side, fieldhouse</Location>
				<Notes></Notes>
				<SummerHours>12:00 pm - 4:00 pm</SummerHours>
				<WinterHours>12:00 pm - 4:00 pm</WinterHours>
			</Washroom>
		</Facilities>
	</Park>
	<Park ID="11">
		<Name>Cardero Park</Name>
		<Official>1</Official>
		<StreetNumber>1601</StreetNumber>
		<StreetName>Bayshore Drive</StreetName>
		<EWStreet>Bayshore Drive</EWStreet>
		<NSStreet>Cardero Street</NSStreet>
		<GoogleMapDest>49.292211,-123.128206</GoogleMapDest>
		<Hectare>0.33</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>West End</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/west_end/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<SpecialFeature>Seawall</SpecialFeature>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="12">
		<Name>Cathedral Square</Name>
		<Official>1</Official>
		<StreetNumber>566</StreetNumber>
		<StreetName>Richards Street</StreetName>
		<EWStreet>Dunsmuir Street</EWStreet>
		<NSStreet>Richards Street</NSStreet>
		<GoogleMapDest>49.282084,-123.113877</GoogleMapDest>
		<Hectare>0.27</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="13">
		<Name>Coal Harbour Park</Name>
		<Official>1</Official>
		<StreetNumber>480</StreetNumber>
		<StreetName>Broughton Street</StreetName>
		<EWStreet>W Hastings Street</EWStreet>
		<NSStreet>Broughton Street</NSStreet>
		<GoogleMapDest>49.289981,-123.125015</GoogleMapDest>
		<Hectare>0.95</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Community Halls</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="14">
		<Name>Coopers' Park</Name>
		<Official>1</Official>
		<StreetNumber>1020</StreetNumber>
		<StreetName>Marinaside Crescent</StreetName>
		<EWStreet>Nelson Street</EWStreet>
		<NSStreet>Marinaside Crescent</NSStreet>
		<GoogleMapDest>49.273253,-123.113900</GoogleMapDest>
		<Hectare>1.71</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Skateboard Parks</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Basketball Courts</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Dogs Off-Leash Areas</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<SpecialFeature>Seawall</SpecialFeature>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="15">
		<Name>Creekside Park</Name>
		<Official>1</Official>
		<StreetNumber>1455</StreetNumber>
		<StreetName>Quebec Street</StreetName>
		<EWStreet>Terminal Avenue</EWStreet>
		<NSStreet>Quebec Street</NSStreet>
		<GoogleMapDest>49.274415,-123.102924</GoogleMapDest>
		<Hectare>2.53</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<SpecialFeature>Seawall</SpecialFeature>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="16">
		<Name>David Lam Park</Name>
		<Official>1</Official>
		<StreetNumber>1300</StreetNumber>
		<StreetName>Pacific Boulevard</StreetName>
		<EWStreet>Drake Street</EWStreet>
		<NSStreet>Pacific Boulevard</NSStreet>
		<GoogleMapDest>49.272569,-123.124145</GoogleMapDest>
		<Hectare>4.34</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Soccer Fields</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Basketball Courts</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Tennis Courts</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<SpecialFeature>Seawall</SpecialFeature>
			<Washroom>
				<Location>West side</Location>
				<Notes></Notes>
				<SummerHours>10:00 am - Dusk</SummerHours>
				<WinterHours>10:00 am - Dusk</WinterHours>
			</Washroom>
		</Facilities>
	</Park>
	<Park ID="18">
		<Name>Devonian Harbour Park</Name>
		<Official>1</Official>
		<StreetNumber>1929</StreetNumber>
		<StreetName>W Georgia Street</StreetName>
		<EWStreet>W Georgia Street</EWStreet>
		<NSStreet>Denman Street</NSStreet>
		<GoogleMapDest>49.294353,-123.134654</GoogleMapDest>
		<Hectare>4.42</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Dogs Off-Leash Areas</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<SpecialFeature>Seawall</SpecialFeature>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="19">
		<Name>Art Phillips Park</Name>
		<Official>1</Official>
		<StreetNumber>625</StreetNumber>
		<StreetName>Burrard Street</StreetName>
		<EWStreet>Melville Street</EWStreet>
		<NSStreet>Burrard Street</NSStreet>
		<GoogleMapDest>49.285911,-123.120948</GoogleMapDest>
		<Hectare>0.1</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="20">
		<Name>Emery Barnes Park</Name>
		<Official>1</Official>
		<StreetNumber>1170</StreetNumber>
		<StreetName>Richards Street</StreetName>
		<EWStreet>Davie Street</EWStreet>
		<NSStreet>Richards Street</NSStreet>
		<GoogleMapDest>49.276458,-123.123995</GoogleMapDest>
		<Hectare>0.85</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Dogs Off-Leash Areas</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="21">
		<Name>Harbour Green Park</Name>
		<Official>1</Official>
		<StreetNumber>1199</StreetNumber>
		<StreetName>W Cordova Street</StreetName>
		<EWStreet>W Cordova Street</EWStreet>
		<NSStreet>Bute Street</NSStreet>
		<GoogleMapDest>49.290263,-123.121924</GoogleMapDest>
		<Hectare>3.1</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Water/Spray Parks</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Restaurants</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<SpecialFeature>Seawall</SpecialFeature>
			<Washroom>
				<Location>Central</Location>
				<Notes></Notes>
				<SummerHours>10:00 am - Dusk</SummerHours>
				<WinterHours>8:00 am - Dusk</WinterHours>
			</Washroom>
		</Facilities>
	</Park>
	<Park ID="23">
		<Name>Helmcken Park</Name>
		<Official>1</Official>
		<StreetNumber>1103</StreetNumber>
		<StreetName>Pacific Boulevard</StreetName>
		<EWStreet>Helmcken Street</EWStreet>
		<NSStreet>Pacific Boulevard</NSStreet>
		<GoogleMapDest>49.274814,-123.119555</GoogleMapDest>
		<Hectare>0.17</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="24">
		<Name>Marina Square</Name>
		<Official>1</Official>
		<StreetNumber>1675</StreetNumber>
		<StreetName>Bayshore Drive</StreetName>
		<EWStreet>Bayshore Drive</EWStreet>
		<NSStreet>Denman Street</NSStreet>
		<GoogleMapDest>49.292334,-123.131296</GoogleMapDest>
		<Hectare>0.63</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<SpecialFeature>Seawall</SpecialFeature>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="25">
		<Name>May &amp; Lorne Brown Park</Name>
		<Official>1</Official>
		<StreetNumber>801</StreetNumber>
		<StreetName>Beach Avenue</StreetName>
		<EWStreet>Beach Avenue</EWStreet>
		<NSStreet>Hornby Street</NSStreet>
		<GoogleMapDest>49.275188,-123.132046</GoogleMapDest>
		<Hectare>0.25</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="26">
		<Name>Pioneer Place (Pigeon Park)</Name>
		<Official>1</Official>
		<StreetNumber>399</StreetNumber>
		<StreetName>Carrall Street</StreetName>
		<EWStreet>W Hastings Street</EWStreet>
		<NSStreet>Carrall Street</NSStreet>
		<GoogleMapDest>49.281699,-123.104588</GoogleMapDest>
		<Hectare>0.03</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="27">
		<Name>Portal Park</Name>
		<Official>1</Official>
		<StreetNumber>1099</StreetNumber>
		<StreetName>W Hastings Street</StreetName>
		<EWStreet>W Hastings Street</EWStreet>
		<NSStreet>Thurlow Street</NSStreet>
		<GoogleMapDest>49.288042,-123.119169</GoogleMapDest>
		<Hectare>0.1</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="28">
		<Name>CRAB Park at Portside</Name>
		<Official>1</Official>
		<StreetNumber>101</StreetNumber>
		<StreetName>E Waterfront Road</StreetName>
		<EWStreet>E Waterfront Road</EWStreet>
		<NSStreet>Main Street</NSStreet>
		<GoogleMapDest>49.284942,-123.102377</GoogleMapDest>
		<Hectare>3.31</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Field Houses</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>2</FacilityCount>
				<FacilityType>Playgrounds</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Water/Spray Parks</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Dogs Off-Leash Areas</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Washroom>
				<Location>South side at fieldhouse</Location>
				<Notes></Notes>
				<SummerHours>7:00 am - Dusk</SummerHours>
				<WinterHours>7:00 am - Dusk</WinterHours>
			</Washroom>
		</Facilities>
	</Park>
	<Park ID="29">
		<Name>Roundhouse Turntable Plaza</Name>
		<Official>1</Official>
		<StreetNumber>181</StreetNumber>
		<StreetName>Roundhouse Mews</StreetName>
		<EWStreet>Roundhouse Mews</EWStreet>
		<NSStreet>Pacific Boulevard</NSStreet>
		<GoogleMapDest>49.273379,-123.121603</GoogleMapDest>
		<Hectare>0.91</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Facility>
				<FacilityCount>1</FacilityCount>
				<FacilityType>Community Centres</FacilityType>
				<FacilityURL></FacilityURL>
			</Facility>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="30">
		<Name>Sun Yat-Sen Gardens</Name>
		<Official>1</Official>
		<StreetNumber>578</StreetNumber>
		<StreetName>Carrall Street</StreetName>
		<EWStreet>Keefer Street</EWStreet>
		<NSStreet>Carrall Street</NSStreet>
		<GoogleMapDest>49.279691,-123.104233</GoogleMapDest>
		<Hectare>0.83</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="31">
		<Name>Victory Square</Name>
		<Official>1</Official>
		<StreetNumber>200</StreetNumber>
		<StreetName>W Hastings Street</StreetName>
		<EWStreet>W Hastings Street</EWStreet>
		<NSStreet>Cambie Street</NSStreet>
		<GoogleMapDest>49.282218,-123.110133</GoogleMapDest>
		<Hectare>0.39</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="32">
		<Name>Wendy Poole Park</Name>
		<Official>1</Official>
		<StreetNumber>199</StreetNumber>
		<StreetName>Alexander Street</StreetName>
		<EWStreet>Alexander Street</EWStreet>
		<NSStreet>Main Street</NSStreet>
		<GoogleMapDest>49.284296,-123.099666</GoogleMapDest>
		<Hectare>0.04</Hectare>
		<Neighbourhood>
			<NeighbourhoodName>Downtown</NeighbourhoodName>
			<NeighbourhoodURL>http://vancouver.ca/community_profiles/downtown/index.htm</NeighbourhoodURL>
		</Neighbourhood>
		<Advisories></Advisories>
		<Facilities>
			<Washroom></Washroom>
		</Facilities>
	</Park>
	<Park ID="34">
		<Name>Balaclava Park</Name>
		<Official>1</Official>
		<StreetNumber>4594</StreetNumber>
		<StreetName>Balaclava Street</StreetName>
		<EWStreet>W 29th Avenue</EWStreet>
		<NSStreet>Balaclava Street</NSStreet>